### ISSUE TITLE
SF Meetup: Concurrency and Parallelism

### ISSUE THREAD

**Issue by erickt** [rust-community/talks#1]
Potential speakers / projects:

* [x] @aturon (SF): https://github.com/aturon/crossbeam
* [ ] @nikomatsakis (Boston): https://github.com/nikomatsakis/rayon (interested, may time around SF visit, or remote)
* [ ] @huonw (Australia): https://github.com/huonw/simple_parallel (remote)
* [ ] ~~@gamazeps (France): https://github.com/gamazeps/RobotS~~

**Comment by gamazeps** [comment]
Hey @erickt that sounds pretty cool to have concurrency talks :)

I'm up for doing a talk if someone wants, but I'd rather wait to land the networking module in my crate before presenting it (it would be a bit short otherwise).

PS: I'm located in France :p

**Comment by erickt** [comment]
@gamazeps no worries! I also understand it'd also be a bit tricky for you. Perhaps the [Rust Paris](http://www.meetup.com/Rust-Paris/) meetup would be a better venue? cc-ing @pnkfelix

**Comment by erickt** [comment]
@aturon, @nikkomatsakis, @huonw: How does Thursday, January 14th sound? @brson, is the room available that day?

**Comment by pnkfelix** [comment]
@erickt are you planning to have all these speakers present on same day?  If so, what is the target time range?  (If it is pacific evening then yes, France time zone may be problematic )  just trying to establish overall context..

**Comment by aturon** [comment]
I'm game!

**Comment by erickt** [comment]
@pnkfelix: Hi! No I wasn't trying to coordinate our meetups, I was just passing @gamazeps off to you in case you were looking for speakers :) I'll open up a separate ticket to make it easier to track any other European concurrency projects I come across.

**Comment by brson** [comment]
I've reserved the room and scheduled airmo.

**Comment by erickt** [comment]
thanks @brson! @nikomatsakis / @huonw: does this day work for you?

**Comment by huonw** [comment]
I think it works for me, but I can't guarantee it.

**Comment by aturon** [comment]
Would definitely be good to do this when Niko is going to be in town, but
that may not be feasible if you want this to be the next meetup.

**Comment by gamazeps** [comment]
If someone interested I can remote, even though I don't feel I have much to say :)

**Comment by erickt** [comment]
@nikomatsakis: Do you know when you're next in town? Are you planning a visit in January or February? If not, I'd like to go ahead with this so we get back on a regular meetup schedule.

**Comment by erickt** [comment]
@gamazeps: thanks for the offer! I think we're good this time around, but if you are okay with waking up super early, perhaps we could line you up with another meetup?

**Comment by aturon** [comment]
cc'ing Niko directly, just in case.

**Comment by nikomatsakis** [comment]
@erickt no planned visit yet.

**Comment by pnkfelix** [comment]
@erickt FYI, if you do line @gamazeps up for another meetup, I will be happy to coordinate letting him into the Paris office (super early, as you note) in case he would prefer to deliver his presentation from here.

(But then again, with it being super early and all, perhaps @gamazeps will be happier delivering the presentation from the comfort of his own home.)

**Comment by erickt** [comment]
thanks @nikomatsakis, @aturon, and @huonw! It was a great meetup. If you're interested in sharing your slides, would you mind sending them to me? Also, please use a license to make it clear how our community could reuse them. I'd suggest one of the [Creative Commons](https://creativecommons.org/) to make it easy.

Here's the [video](https://air.mozilla.org/bay-area-rust-meetup-january-2016/) if anyone wants to see it.

**Comment by huonw** [comment]
http://huonw.github.io/simple_parallel-jan16/slides.html (The content of the slides is CC BY 4.0.)
