### ISSUE TITLE
SF: April

### ISSUE THREAD

**Issue by erickt** [rust-community/talks#11]
@cmr: [Robigalia](https://robigalia.org/): Building a robust Rust ecosystem around seL4

**Comment by cmr** [comment]
(Will likely be the same fundamental presentation as https://github.com/RustSydney/talks/issues/12. although with few weeks of additional progress)

**Comment by erickt** [comment]
potentially @jethrogb on https://github.com/jethrogb/sgx-utils.

**Comment by erickt** [comment]
@jethrogb is unavailable on 3/17, 3/24, 4/21.

**Comment by steveklabnik** [comment]
I could do a remote talk about @intermezzOS

**Comment by erickt** [comment]
@steveklabnick: that would be delightful! You and @cmr should sync up some time to make sure you don't overlap too much.

**Comment by erickt** [comment]
@cmr / @jethrogb / @steveklabnik: Still interested in speaking at the April meetup? Say April 28? If so, how long would you like to speak for?

**Comment by jethrogb** [comment]
That works for me. I can talk anywhere from 10 to 45 minutes, not sure what is appropriate.

**Comment by steveklabnik** [comment]
Same, I should be good, yeah

**Comment by cmr** [comment]
That sounds good! I can fit in the same time constraints, although if it's to be technical it will want to be closer to 45-60 minutes.

**Comment by cmr** [comment]
Basically: what message are we trying to get across?

I can talk about microkernels, sel4, driver dev, trustworthy/high-assurance systems in general, (hw) architectural concerns of OS's, how to use some of the libraries I've been working on for robigalia, etc. It'd be nice for our talks have some level of coherence and good ordering.

**Comment by jethrogb** [comment]
The SGX stuff is largely orthogonal, although some microkernel/unikernel concepts can apply, so it might be best if I go last. Although it doesn't matter too much.

**Comment by erickt** [comment]
@steveklabnik: how long do you think you'd want to speak for? If it's also long, perhaps we should bump you to a future meetup?

@jethrogb: do you think you would be in person, or remote?

all: How does April 21 or April 28 look to everyone, starting around 7pm PST?

**Comment by jethrogb** [comment]
Both work for me. I'll be there in person.

**Comment by cmr** [comment]
I prefer the 28th.

**Comment by erickt** [comment]
I'll aim for the 28th then. I'll let you know if we can lock it in.

**Comment by erickt** [comment]
@cmr / @jethrogb: Drat, the 28th has already been taken. How does Tuesday 4/26 look for you two? Or Thursday, 5/5?

cc @brson

**Comment by jethrogb** [comment]
Both work for me.

**Comment by brson** [comment]
The room is booked for 4/26, but we can still change it if necessary.

**Comment by erickt** [comment]
@cmr: does 4/26 work for you?

**Comment by cmr** [comment]
Yes.

**Comment by cmr** [comment]
@erickt I notice there's no "upcoming meetup" thingy on meetup.com for this event yet.

**Comment by erickt** [comment]
@cmr: It's been announced! http://www.meetup.com/Rust-Bay-Area/events/230271083/

**Comment by cmr** [comment]
How long should each of our talks be, or rather, how much time is allocated in total for talks?

**Comment by erickt** [comment]
@cmr: There is a max time of 1:30. How much time do you want? I thought you said you wanted 45-60 min in the email thread.

**Comment by brson** [comment]
@cmr @jethrogb The AV folks like to get slides ahead of time. Can you email your decks to me or @erickt by monday night?

**Comment by erickt** [comment]
@jethro: they also want to know if you have a laptop and if so, what kind is it, and what video output ports does it have?

**Comment by jethrogb** [comment]
Yeah I talked to @brson about this. My laptop has VGA and full-size DisplayPort.
