### ISSUE TITLE
SF: March

### ISSUE THREAD

**Issue by erickt** [rust-community/talks#12]
Possible speakers:
- @bluss (remote) on [ndarray](https://github.com/bluss/rust-ndarray)
- @hobofan / @MichaelHirn (remote) on [leaf](https://github.com/autumnai/leaf) and [collenchyma](https://github.com/autumnai/collenchyma)

**Comment by erickt** [comment]
Tentatively @dherman on [neon](https://github.com/rustbridge/neon), if this month works for you.

**Comment by erickt** [comment]
@bluss / @hobofan / @MichaelHirn / @danburkert: You all ready for next week? We should test out your cameras / microphones to make sure our AV equipment is setup correctly. Also, if you are making slides, could you make them in the 16:9 layout? Thanks!

**Comment by bluss** [comment]
Ready. Yes I'd love to do some tech rehearsal. Primary alternative would be vidyo? I'd love advice on best program to set up on debian/testing (stretch).

**Comment by erickt** [comment]
@bluss: Yeah, Mozilla AV prefers vidyo. I'm working on getting a test setup working for you. I'll mail you offline when I get a link. Hopefully I'll also get debian setup instructions for you too. If we can't get that to work, are you able to also do Skype or Google Hangouts?

**Comment by bluss** [comment]
Great! Yes I think so.

**Comment by MichaelHirn** [comment]
Hey @erickt. We are ready.

Looking forward to the tech rehearsal. I have access to an Arch Linux machine and potentially a Mac. In any case, Google Hangouts should work for us.

**Comment by danburkert** [comment]
I'm ready. I'll be in person, do I need to do anything special?

-- Dan
