### ISSUE TITLE
SF: May

### ISSUE THREAD

**Issue by erickt** [rust-community/talks#13]
Potentially:

@alevy on [Tock](https://github.com/helena-project/tock)
@johanneskoester on [rust-bio](https://github.com/rust-bio/rust-bio)

**Comment by erickt** [comment]
@AtheMathmo: Would you be interested in speaking about [rusty-machine](https://github.com/AtheMathmo/rusty-machine) for the May meetup?

**Comment by erickt** [comment]
May would work for @dherman. How does Thursday, May 19 look for everyone?

@AtheMathmo: I might need to bump you to June.

**Comment by AtheMathmo** [comment]
@erickt Very interested in speaking. Either May or June would work for me - let me know :)

**Comment by alevy** [comment]
Later in May (say, the following week) or first two weeks of June would be much better for me if possible.

**Comment by erickt** [comment]
How would a tentative June 2nd work for you all?

**Comment by AtheMathmo** [comment]
I have family visiting and they will be flying back on the 2nd - not sure on the time yet. It may work out fine but I'll have to confirm in a couple days.

**Comment by johanneskoester** [comment]
For me it would work, although I would prefer a few days later to be honest. But I can make it if it is the best date for the rest.

**Comment by alevy** [comment]
June 2nd works for me, as does any day until June 14th or so.

**Comment by erickt** [comment]
We might be able to do the following week, so Thursday June 9th if that would work better for everyone. @brson: can we get the room reserved for that day?

**Comment by erickt** [comment]
Hello @brson / @alevy / @johannesskoester / @AtheMathmo: it seems like our window is closing for early June. How does the end of June look? Say June 23rd?

**Comment by johanneskoester** [comment]
Works for me!

**Comment by AtheMathmo** [comment]
Yup, June 23rd looks good for me. Thanks for organizing this Erick!

**Comment by alevy** [comment]
Folks, sorry, I have to be out of the country at the end of June. It looks like I might have to regrettably bow out. Sorry!

**Comment by alevy** [comment]
To clarify, if we can do the first half of June I would love to, but I obviously understand there are other constraints y'all have to abide by.

**Comment by AtheMathmo** [comment]
@erickt do we have any updates on this? I'm still very keen to talk!

**Comment by erickt** [comment]
@AtheMathmo: great! I'm waiting to hear back on the room, but I really want to get this to happen.

@alevy: how does your July / August look?

**Comment by erickt** [comment]
Well June never happened, so lets try for July. @alevy / @brson / @johanneskoester: how does Thursday July 28th look for everyone?

**Comment by johanneskoester** [comment]
Works for me. @erickt, thanks for your continuous effort to organize this!!

**Comment by AtheMathmo** [comment]
Good for me too. Thanks @erickt !

**Comment by brson** [comment]
@erickt I've booked the room and airmo support for July 28.

**Comment by erickt** [comment]
\o/ Lets do this! @johanneskoester and @AtheMathmo, can you give me a brief description of your talk? @alevy: please let me know if you can participate locally or remotely!

**Comment by AtheMathmo** [comment]
@erickt Awesome! I'm happy to put together a brief description but would also like to put together a survey like I saw someone else do before. As I'll be talking about some quite domain specific stuff it would be good to know how much people want me to go into specifics. Are you happy for me to do that?

**Comment by alevy** [comment]
Looks like I actually might be able to do it locally

**Comment by erickt** [comment]
@alevy: wonderful!

@AtheMathmo: sure! That happened in this meetup: http://www.meetup.com/Rust-Bay-Area/events/230271083/. Feel free to just point me to your survey and I'll add it to the announcement.

**Comment by AtheMathmo** [comment]
@erickt - Thanks for the link.

Here's the survey: https://docs.google.com/forms/d/1vECiA0OXlBUCs-O94-dIzuIDKSf_cfpQ-AFD7_te7h4/viewform

And for a brief description:

[Rusty-machine](https://github.com/AtheMathmo/rusty-machine) - Writing a machine learning library in Rust that works out-of-the-box.

Wasn't sure how brief to be... Let me know if I should say more.

**Comment by erickt** [comment]
Meetup has been announced!: http://www.meetup.com/Rust-Bay-Area/events/232406852/

**Comment by AtheMathmo** [comment]
Thanks @erickt ! Would you mind adding the survey too? I want to make sure I bore the audience as little as possible :)

Really looking forward to seeing you all there!

**Comment by alevy** [comment]
@erickt great! How long should we plan our talks for?

**Comment by erickt** [comment]
@alevy: we typically go up to about an hour and a half, but we can do 2 hours. So I'd aim for about 30 minutes, but let me know if you need more.

**Comment by alevy** [comment]
Also, would it be possible to switch around the order of the talks? I'll be coming up from Mountain View that evening, and should be able to make it on time, but just in case... If it's possible to just play it by ear, that's fine with me too. Sorry for the inconvenience!

**Comment by erickt** [comment]
@alevy: shuffled! @AtheMathmo and @johanneskoester, how are you on the ordering?

**Comment by AtheMathmo** [comment]
@erickt: Fine by me. Thanks for adding the survey too!

**Comment by erickt** [comment]
@AtheMathmo: sorry I left it off at first!

**Comment by johanneskoester** [comment]
@erickt: Any ordering is ok!

**Comment by johanneskoester** [comment]
@erickt since I won't be there in person, how will I be able to present technically. Is the remote functionality for https://slides.com ok for you? I would basically control a presentation in your browser from here. I only need a way to transfer my speech to you (e.g. via skype or hangout?).

**Comment by erickt** [comment]
Hello everyone! @AtheMathmo / @alevy / @johanneskoester: You all ready for tomorrow? Anything I can help out with?

@johanneskoester: I'll reach out to you offline on getting things set up. Let me know if you don't get my email.

**Comment by AtheMathmo** [comment]
@erickt As ready as can be! I have the slides posted up [here](http://athemathmo.github.io/2016/07/28/rusty-machine-talk.html#/)

If it wont be possible to access them let me know and I'll to figure something else out.. Looking forward to seeing you all!

**Comment by alevy** [comment]
I just have to cut down a 1 hour talk to 30 minutes - in other words improve it. But otherwise set!
