### ISSUE TITLE
Berlin July 2016

### ISSUE THREAD

**Issue by johannhof** [rust-community/talks#23]
It would be great to get another meetup going for end of July or sometime in August. Before Rustfest.

@skade last meetup we had several people who said they want to give a talk, can you note down the people you remember so that we can contact them? I'll try to come up with a list as well.

Todo: 
- [x] Date: **July 27 7pm**
- [x] Venue: **Blacklane**
  - [x] Drinks
  - [ ] try!(Food)
- [x] Speakers
  - [x] 1: @aepsil0n 
  - [x] 2: @ligthyear
  - [ ] 3: Option\<Speaker\>
- [x] http://www.meetup.com/Rust-Berlin/events/232583152/
  - [x] Announcement 

cc @fhartwig

**Comment by johannhof** [comment]
@aepsil0n would __July 27__ work for you to talk about carboxyl?

**Comment by aepsil0n** [comment]
@johannhof Yes, that works for me.

**Comment by johannhof** [comment]
Awesome! Let's try for July 27th then! I'll reach out to venues.

**Comment by johannhof** [comment]
@ligthyear we were chatting this afternoon if you could do a talk e.g. about arewewebyet (or maybe clippy/clippy-service?)

Would the 27th work for you?

**Comment by ligthyear** [comment]
@johannhof how long and at what level should talks be? Also at what time would we start? I have a company dinner to attend that day, but could see that I leave early enough.

**Comment by johannhof** [comment]
@ligthyear we usually start at around 7pm (which means we wait until at least 7:15-7:20 for people to arrive)

We had both beginner-friendly and more complex talks that were well received I think, although I'm sure a lot of people would appreciate an entry-level talk on e.g. state of web development.

20-40 min? Again, talks differ a lot in that but nobody minds.

Thanks!

**Comment by johannhof** [comment]
Blacklane is up for hosting again!

**Comment by ligthyear** [comment]
Ok, I think I can do a talk about clippy-as-a-service, like a 20minute "Your first Web-Service with Rust"-Talk. And briefly go into AreWeWebYet and the general state of the Rust Web, encouraging people to build rust web stuff.

So, feel free to announce me as the second talk.

**Comment by johannhof** [comment]
@aepsil0n @ligthyear could you send me an email with a short talk summary?

**Comment by johannhof** [comment]
Happened! Thanks everyone!
