### ISSUE TITLE
SF: November 2016

### ISSUE THREAD

**Issue by erickt** [rust-community/talks#25]
Todo:
- [ ] Pick a date: November 17 / December 1?
- [ ] Speakers
  - [x] @dherman: Want to speak about [neon](https://github.com/rustbridge/neon)?
  - [ ] @wycats / @chancancode: Want to speak about [helix](https://github.com/rustbridge/helix)?
  - [ ] @jameysharp: Want to speak about [corrode](https://github.com/jameysharp/corrode)?
  - [ ] @japaric: embedded rust / xargo
  - [x] @jonathandturner: rust language server

cc @brson

**Comment by jameysharp** [comment]
I would love to come speak about Corrode! But as I'm currently unemployed I'm not sure I can justify the travel cost, even though we're on the same coast. I don't suppose you have any budget for speaker travel? If not, perhaps I should present at the Portland Rust meetup sometime instead.

**Comment by erickt** [comment]
@jameysharp: I unfortunately don't have a budget, but we could also do a remote talk if you have a web camera and microphone. I'd also be happy to introduce you to the folks behind [PDXRust](http://www.meetup.com/PDXRust/), @edunham and I think @MDCox?

**Comment by erickt** [comment]
@emilio on the servo fork of bindgen to automatically generate rust code to bind to c++ libraries.

**Comment by edunham** [comment]
@erickt, we've followed up on this by scheduling Jamey's Corrode talk for the PDXRust September meeting, http://www.meetup.com/PDXRust/events/232597522/. As usual, the talk will be recorded and available online unless we encounter unexpected AV difficulties with the office's setup.

**Comment by erickt** [comment]
@edunham: Great! I look forward to seeing it :)
