### ISSUE TITLE
Rust NYC Sep meetup

### ISSUE THREAD

**Issue by frewsxcv** [rust-community/talks#29]
There's been talk of doing a Rust NYC meetup in September or October. Nothing too concrete at the moment, but opening an issue here for the discussion.

**Comment by frewsxcv** [comment]
https://www.meetup.com/Rust-NYC/events/233756447/

**Comment by frewsxcv** [comment]
@erickt Any chance this could get added to the community calendar?

**Comment by erickt** [comment]
I gave @frewsxcv access!
