### ISSUE TITLE
SF: December 2016

### ISSUE THREAD

**Issue by erickt** [rust-community/talks#30]
Todo:
- [ ] date: December 15?
- [ ] @dtolnay on syn / macros 1.1?
- [ ] @wycats / @chancancode on helix?
- [ ] @sfackler on Binding to C in Rust - but trust me it's not booooooooooring

**Comment by dtolnay** [comment]
@erickt I see that I am listed first on the Meetup but just to confirm - I would like to present first if possible.

**Comment by erickt** [comment]
@dtolnay sure that's fine.
