### ISSUE TITLE
Cambridge Raspberry Jam: Rust on the Raspberry Pi

### ISSUE THREAD

**Issue by thejpster** [rust-community/talks#33]
I'm giving a talk at the Cambridge Raspberry Jam on 3 December. It will be a gentle introduction to Rust, with live examples on my Raspberry Pi 3.

http://camjam.me/

**Comment by booyaa** [comment]
@thejpster any chance we could have you repeat the talk for london rust meetup group next year?

**Comment by thejpster** [comment]
I'm sure that could be arranged.

I'd actually like to start up a Cambridge Rust user group, but that's a topic for another thread perhaps.

**Comment by booyaa** [comment]
yup best to raise that a new issue. i'm on #rust-community if you do irc and want to run some thought past me (i'm the London meetup organiser).

**Comment by thejpster** [comment]
Talk here: https://www.youtube.com/watch?v=6O4OCU45Djo
