### ISSUE TITLE
SF: January 2017

### ISSUE THREAD

**Issue by erickt** [rust-community/talks#34]
Candidates:

- [ ] @jwilm on [alacrity](https://github.com/jwilm/alacritty)?
- [ ] @jameysharp on [corrode](https://github.com/jameysharp/corrode)
- ???

**Comment by jwilm** [comment]
I could make that work! For scheduling, later in the month is preferable if that's possible.

**Comment by erickt** [comment]
how about a tentative January 26? @jameysharp, is that what we were thinking?

**Comment by jwilm** [comment]
that sounds like a really great date

**Comment by jameysharp** [comment]
We'd been talking about January 19th, which would be better for me, if
that's OK with you all?

**Comment by erickt** [comment]
@jwilm: that work for you?

**Comment by erickt** [comment]
@jwilm: also, Jamey will be coming in from out of town for the talk, so he gets preference :)

**Comment by jwilm** [comment]
That works for me

**Comment by michaelsproul** [comment]
I'm available to do a (remote) talk about [aus_senate](https://github.com/michaelsproul/aus_senate) on the 19th

(moving this conversation here from reddit: https://www.reddit.com/r/rust/comments/5drfuz/computing_the_result_of_the_2016_australian/da6vo9h/)

**Comment by erickt** [comment]
Great! @michaelsproul, @jwilm, and @jameysharp: we got the room for the 1/19! I'll see you that night!!

**Comment by jameysharp** [comment]
Is this event in the San Francisco Mozilla office?

**Comment by erickt** [comment]
@jameysharp yes it will be.

**Comment by Manishearth** [comment]
Yep. They always are.

**Comment by erickt** [comment]
Also, @jameysharp / @michaelsproul / @jwilm: can each of you give me a sentence or two describing your talks for the meetup announcement?

**Comment by jwilm** [comment]
Alacritty - A cross-platform, GPU enhanced terminal emulator

**Comment by michaelsproul** [comment]
*How to calculate a nation state's election result in your bedroom*: The algorithm for deciding Australian senate elections is quite complex, and despite pressure from the public, there is no reference implementation available. I'll talk about how I re-implemented it in Rust, handling gigabytes of ballot papers and crunching millions of rational numbers in the process.

**Comment by michaelsproul** [comment]
@erickt: What will the set up be like for me presenting remotely? Is there a specific bit of screen-sharing software that people usually use? We can chat via email to avoid spamming this thread if you like (I'm `micsproul` blahblah `gmail.com`).

**Comment by erickt** [comment]
@jameysharp howdy! I just wanted to check in and see how things are coming along. You ready for Thursday?

**Comment by jameysharp** [comment]
@erickt I'll be there! I've been meaning to ask, how long do you want each presentation to be? Given that there are three talks, should I be aiming for 30 minutes including questions?

Also, I'm currently planning to spend Thursday at the Mozilla San Francisco office, and Friday at the Mozilla Mountain View office, if anybody wants to say hi!

**Comment by Manishearth** [comment]
Heh, might come down to MTV on Friday then, haven't done so in a while.

**Comment by Manishearth** [comment]
(See you at the office on Thursday, anyway!)

**Comment by erickt** [comment]
@jameysharp: 30 minutes would be great!

**Comment by jwilm** [comment]
My train has been sitting at the San Antonio station for 25 minutes. Maaaay be running a bit late if caltrain doesn't get moving soon (apparently there's been an incident). Will grab an Uber to Mozilla once i'm up there.

**Comment by jwilm** [comment]
Finally moving :)

**Comment by frewsxcv** [comment]
Can this be closed?
