### ISSUE TITLE
CAMBRIDGE: July 2017

### ISSUE THREAD

**Issue by jonathanpallant** [rust-community/talks#52]
- [ ] Date: TBD
- [ ] Theme: None
- [ ] Venue: Cambridge Consultants?
- [ ] Sponsors: Cambridge Consultants
- [ ] Speaker(s):
- 7PM - @thejpster - Announcements
- TBD
- [ ] Post event write up on URLO.

Announcements:
- (Pull interesting stuff from TWIR)
- TBD

**Comment by aidanhs** [comment]
One of the three talks I'm consider for the June talk is not particularly specific to my experience, so if someone would like to talk but isn't sure about the topic, I could write a few notes on it/talk it through with them as possible inspiration. Bit more study-group themed, "here's an interesting topic I've been looking into related to rust".

**Comment by thejpster** [comment]
Meeting complete.
