### ISSUE TITLE
Berlin: September 2017 🐼

### ISSUE THREAD

**Issue by johannhof** [rust-community/talks#54]
- [x] Date: **12th of September @ 6:45PM (talks begin @ 7:15PM)**
- [x] Venue: **[Mozilla Berlin](https://www.mozilla.org/en-US/contact/spaces/berlin/)** [♿️ ](https://wheelmap.org/en/nodes/4996803917)
- [x] Food & Drinks sponsored by **Mozilla** (Make a ticket)
- [x] Agenda/Talks
  - [x] 7:15PM - Welcome & Announcements
  - [x] 7:20PM - **@celaus** on **sensors**
  - [x] 7:50PM - **@emilio** on **Servo**
- [x] Meetup Page: https://www.meetup.com/Rust-Berlin/events/242564404/
- [x] Meetup Announcement
- [x] Twitter Announcement: https://twitter.com/RustBerlin/status/903217026079924224

cc @skade

**Comment by johannhof** [comment]
@emilio we talked about this in person, would you be available for a talk at one of these dates?

**Comment by booyaa** [comment]
Would it be okay if we also asked @emilio to do an encore of their talk (remotely) for the London Meetup in October? https://github.com/rust-community/talks/issues/47

**Comment by skade** [comment]
I'll have to check my availability, it occured to me that September 11th is my mothers birthday. :)

**Comment by johannhof** [comment]
Added a wheelchair accessibility status, since our new office is finally built to be fully accessible!

**Comment by skade** [comment]
\o/

**Comment by emilio** [comment]
> @emilio we talked about this in person, would you be available for a talk at one of these dates?

Just confirmed, yeah, both of the dates are fine :)

**Comment by johannhof** [comment]
> Just confirmed, yeah, both of the dates are fine :)

Awesome, thank you.

**Comment by johannhof** [comment]
@celaus thanks for offering to talk about Habitat. You mentioned that your colleague could do an additional talk on the topic, which sounds great in general, though I'd like to keep this meetup at two talks.

Would you be fine with either
- sharing a 20-45 minute slot for a joint presentation or
- one of you doing a talk in October? (we already have another speaker for October, so that's very likely to happen)

Let me know what works best for you! Thanks!

**Comment by celaus** [comment]
Thanks @johannhof, that's great! I think two separate talks would be best, but I'd be talking about sensors, my friend (@therealpadams) would be talking about habitat.sh. I don't know his availability in October tough 😄

**Comment by therealpadams** [comment]
I'm always happy to talk about Habitat!

What date are you planing for October?
- October 10, 11 is Chef Community Summit in London
- October 21, 22 is All Systems Go in Berlin
- October 22 - 26 is Linux Foundation's Open Source Summit in Prague

**Comment by johannhof** [comment]
@celaus awesome, thanks for the clarification. It would be great if you could send me a quick talk description for the meetup page!

@emilio I'd love to get a really short talk summary from you as well, whenever you get around to it.

@therealpadams Great! I'll make an issue with possible dates with regards to your schedule then.

Thanks everyone!

**Comment by celaus** [comment]
@johannhof 

rust ❤️ sensors

With Rust being a safe and efficient language, it's perfect for embedded and more lower level applications. However, its ecosystem is missing a crucial thing to succeed: Drivers. More often than not reference implementations are in C or Python, and re-implementing them using that code or even the data sheet is often tricky. This talk will explore available drivers, common pitfalls, and show the audience how to implement their own drivers for i2c devices. 


bio: 

A software engineer by trade, Claus runs field engineering at Crate.io, the creators of CrateDB, a distributed SQL database. As a former CTO of a health startup and an Raspberry Pi and Rust (the programming language) enthusiast, Claus also maintains several drivers for sensors in the Rust community. He loves connecting with developers to talk about putting machine data to work in exciting IoT systems.

**Comment by johannhof** [comment]
Ok, great, thank you.

I will announce the meetup in a second.

@emilio can I get a description of your talk? :)

**Comment by emilio** [comment]
On 08/31/2017 01:14 PM, Johann Hofmann wrote:
> @emilio <https://github.com/emilio> can I get a description of your talk? :)

Sure, does "an overview of Servo's architecture" sound ok? I can
definitely try to use a more fancy name, but I'm not too good at that :)

I can try to elaborate a bit more if you want, I guess :)

**Comment by johannhof** [comment]
@emilio @celaus 

I will ask for AVOps support, so that we can record your talks. I think we have a great setup that should give you really high quality recordings, and I'd love to put the meetup on Air Mozilla and the Rust YouTube channel. I'm not 100% sure if we can live-stream on AirMo, but we might.

Let me know if either of you are not comfortable with a recording or a live stream.

**Comment by johannhof** [comment]
@emilio @celaus 

Assuming you're fine with recording/streaming, I'd need to know the following:

- What file format will your presentation have (PDF, Keynote, ...)?
-  16:9 or 4:3?
- Are you showing any special content such as doing a live demo or playing a video?

Thanks!

Johann

**Comment by celaus** [comment]
@johannhof I'll show a live demo and my slides are usually PDF 16:9

**Comment by johannhof** [comment]
Meetup was a huge success! Thank you everyone and especially @celaus and @emilio for two amazing talks.

The meetup recording is here: https://air.mozilla.org/rust-berlin-meetup-september-2017/

AVOps extracted the individual talks for me (I'll share the folder with both of you) and I will upload them to the official Rust YouTube channel if you're okay with that.

:tada:
