### ISSUE TITLE
LDN : May 2018

### ISSUE THREAD

**Issue by booyaa** [rust-community/talks#65]
If you can't do a talk this month what about next month: #66? 

- [x] Date: **May 2nd @ 6:30PM**
- [x] Theme: Coding Dojo
- Comms
  - [x] Skillsmatter RSVP https://skillsmatter.com/meetups/10919-ldn-coding-dojo-may-2018
  - [x] Meetup RSVP https://www.meetup.com/Rust-London-User-Group/events/249261194/
  - [x] Twitter announcement https://twitter.com/booyaa/status/987268131365244929
  - [ ] [Herald](http://herald.community.rs) `__LINK__`
  - [ ] [URLO](https://users.rust-lang.org/c/community) `__LINK__`
- [x] Venue: **Skillsmatter**
- [ ] Sponsors
  - [ ] `Option`
- [ ]  Speaker(s) Format (max 1hr unless special event/themed): Main Speaker (25m max) + 3 x lightning talks (5-10m) = 55m 
  - [x] **@booyaa** - Announcements
  - [x] Peter Marks begins coding dojo. ([repo](https://github.com/petermarks/rust-ldn-dojo))
- [ ] Post event write up on URLO.

**Announcements**
- [ ] `stuff.unwrap()`

cc @ernestkissiedu , @aidanhs, @fluffyemily , @bradfier
 # URLO (delete after posting)

```
__TITLE__
London Rust Meetup __MONTH__ 2018

__BODY__
**When**: __DATE__ @ 6:30PM
**Where**: Skills Matter | CodeNode
**What**: A Rust meetup in the capital!
**Meetup RSVP Link**: __LINK__
**Twitter Announcement**: __LINK__
**Speakers**:
- TBC

Still looking for speakers (remote is welcome), please comment on the related GitHub issue __LINK__ if interested.
```

**Comment by dwijnand** [comment]
Link to Peter's talk: https://skillsmatter.com/skillscasts/11699-coding-challenges-as-a-learning-tool
and repo: https://github.com/petermarks/compare_input

**Comment by dwijnand** [comment]
They were meant for where it says "(link)" in yesterday's https://www.meetup.com/Rust-London-User-Group/events/249261194/ 😉 (I should've said that to start with..)

**Comment by ernestkissiedu** [comment]
Hi All, 

First off I want to apologise for not being able to make yesterday’s MeetUp and not communicating it either, I’ve had a big deadline and presentation due in today (a few hours from now) and I’ve been totally under it trying to get things done. 
I hope to catch up with you all soon and I’ll be engaging a lot more from next week

Thanks for you understanding 

Regards

Ernest Kissiedu
