### ISSUE TITLE
LDN : June 2018 Show and Tell

### ISSUE THREAD

**Issue by booyaa** [rust-community/talks#66]
Short URL: https://bit.ly/showtellrust2018-1

**If you are going to participate in the show and tell please comment below with the following information:**

- Your name
- Your project/demo
- Time needed (5-10m, can be longer but check with team first)

___

**Admin stuff, ignore**

- [ ] Date: **June 26th @ 6:30PM**
- [ ] Theme: Show and Tell
- Comms
  - [ ] Skillsmatter RSVP `__LINK__`
  - [ ] Meetup RSVP https://www.meetup.com/Rust-London-User-Group/events/249293493/
  - [ ] Twitter announcement `__LINK__`
  - [ ] [Herald](http://herald.community.rs) `__LINK__`
  - [ ] [URLO](https://users.rust-lang.org/c/community) `__LINK__`
- [ ] Venue: **Skillsmatter**
- [ ] Sponsors
  - [ ] `Option`
- [ ]  Speaker(s)
  - [ ] **@booyaa** - Announcements
  - [ ] Lightning Talks 5-10m max
- [ ] Post event write up on URLO.

**Announcements**
- [ ] `stuff.unwrap()`

 # URLO (delete after posting)

```
__TITLE__
London Rust Meetup __MONTH__ 2018

__BODY__
**When**: __DATE__ @ 6:30PM
**Where**: Skills Matter | CodeNode
**What**: A Rust meetup in the capital!
**RSVP Link**: __LINK__
**Twitter Announcement**: __LINK__
**Speakers**:
- TBC

Still looking for speakers (remote is welcome), please comment on the related GitHub issue __LINK__ if interested.
```

**Comment by bootandy** [comment]
I would like to do a talk:

Andrew Boot

Dust. https://github.com/bootandy/dust

Time : 5 minutes.

**Comment by dwijnand** [comment]
* Name: Dale Wijnand
* Project: https://github.com/dwijnand/sbtl
* Time needed: 5m

**Comment by 46bit** [comment]
* **Name:** Michael Mokrysz
* **Project:** https://github.com/46bit/tilewater
* **Time:** 10m

**Comment by 46bit** [comment]
Oh dear, I can't be there! 😞 Next time?

**Comment by petr-tik** [comment]
Name: Peter T
(First ever Rust) Project: [Limit order book](https://github.com/petr-tik/dark_rusty_pool)
Time: 5m

**Comment by xd009642** [comment]
I could do a talk if people would be interested:
Name: Daniel McKenna
Project: https://github.com/xd009642/tarpaulin 
Time 10m

**Comment by Amanieu** [comment]
Name: Amanieu d'Antras
Project: Writing a binary translator in Rust
Time: 15m

**Comment by alecmocatta** [comment]
Would love to do a talk if there're still slots available!
Name: Alec Mocatta
Project: Distributed programming in Rust https://github.com/alecmocatta/deploy
Time: 10m

**Comment by booyaa** [comment]
Thanks everyone! Don't forget to signup using Skillsmatter RSVP (they need an accurate head count for health and safety reasons): https://skillsmatter.com/meetups/11092-rust-london-show-and-tell

**Comment by joetsoi** [comment]
if there's room
Name: Joe T
Project: https://github.com/joetsoi/OpenMoonstone/tree/master/rust
Time: 5m

**Comment by booyaa** [comment]
Thanks everyone! Here's my live tweet of the event: https://twitter.com/booyaa/status/1008979052185751552
